### ISSUE TITLE
requests import issue

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/cvmfs#54]
```python
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/RHEL_7_x86_64/lib/python3.7/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

**Comment by dsschult** [comment]
Going to create py3-v4.2.0 with a Python upgrade as well.

**Comment by dsschult** [comment]
py3-v4.2.0 is deployed
